### ISSUE TITLE
Proposal Generation Only

### ISSUE THREAD

**Issue by Echo0125** [sming256/OpenTAD#17]
Hello, I am interested in performing only the task of Temporal Action Localization and do not want to classify each proposal. Could you please guide me on how to modify the code accordingly?

**Comment by sming256** [comment]
The proposal generation is supported in the next version of OpenTAD, which should be released next week. We will provide BMN/GTAD as an example for temporal action proposal generation task. Stay tuned!

**Comment by sming256** [comment]
Sorry, I just checked. We have already released the proposal generation code in the current version.
Please check here as an [example](https://github.com/sming256/OpenTAD/tree/main/configs/bmn#:~:text=Use%20above%20checkpoints%20to%20evaluate%20the%20recall%20performance%3A).

**Comment by Echo0125** [comment]
Thanks!

**Comment by Echo0125** [comment]
If I want to use actionformer [config](https://github.com/sming256/OpenTAD/blob/main/configs/re2tal/e2e_thumos_actionformer_swin_tiny.py) for e2e-tal without classification, which part of the config do I need to modify? Just modify the rpn_head in [_base_](https://github.com/sming256/OpenTAD/blob/main/configs/_base_/models/actionformer.py)? Thanks!

**Comment by sming256** [comment]
On ActivityNet, ActionFormer sets the `num_classes=1` and uses an external classifier to do classification. If you want to measure their AUC performance, you only need to change the evaluation metric.
```python
evaluation = dict(
    type="Recall",
    subset="validation",
    topk=[1, 5, 10, 100],
    max_avg_nr_proposals=100,
    tiou_thresholds=[0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95],
)
```

On THUMOS, you need to change the `num_classes` to 1 and modify the annotation to have 1 class. 

However, since ActionFormer didn't report their Recall results, so I am not sure whether it is better than BMN or not. If you have more questions about this or need more discussions, please send an email to me at `shuming.liu@kaust.edu.sa`.

**Comment by Echo0125** [comment]
Thanks for your reply! I'll give it a try.
