### ISSUE TITLE
Question about input size

### ISSUE THREAD

**Issue by tongda** [sming256/OpenTAD#28]
Hi, I am very curious about the image size settings. Take [e2e_thumos_videomae_s_768x1_160_adapter](https://github.com/sming256/OpenTAD/blob/main/configs/adatad/thumos/e2e_thumos_videomae_s_768x1_160_adapter.py) as example, input image is resized to **160x160**, but the ViT backbone accept `img_size` as **224**.

May I ask why is that?

**Comment by sming256** [comment]
Since the ViT backbone is trained using 224px, we should keep the `img_size` as 224 when we load the model.
But we can send the video with other resolutions to the backbone, as long as we resize the positional embedding. Please check [here](https://github.com/sming256/OpenTAD/blob/0ecfb265c05f1cfbc6ecefe6dc648a1a14d6a3c6/opentad/models/backbones/vit_adapter.py#L457). In AdaTAD, we are using 160px to save the FLOPS and GPU memory.

**Comment by tongda** [comment]
@sming256 Thank you for so quick reply.

The pos embed resizeing means that the model could accept any size of input. Does it make sense to try larger input size, like 384 or even 640, to distinguish between small actions?

**Comment by sming256** [comment]
Sure. It can accept any size of input. However, I find 256px is usually enough when the model is pre-trained on 224px. If using a larger resolution, the performance may even decrease. Keep in mind that a larger resolution would also cause more memory during training.

**Comment by tongda** [comment]
Got it. Thanks for your explaining.
