### ISSUE TITLE
question about `scale_factor` in AdaTAD

### ISSUE THREAD

**Issue by izikgo** [sming256/OpenTAD#7]
I noticed that for anet you use `scale_factor = 4` to account for the ViT backbone downsampling, but use `scale_factor = 1` for thumos although it uses the same backbone. Can you please explain the logic?

**Comment by sming256** [comment]
This scale factor relates to the number of frames used in the ViT backbone. In concrete, `the actual frame number = window size * scale_factor`. 

Here, the `window size` is the number of features you will have after the backbone, which will be sent into the detector head. On ActivityNet with ActionFormer, it's 192 features.

To get these 192 features, of course, you can sample 192 frames from the video and get 192 features (assume there is no temporal downsampling in the backbone). However, based on the experience in offline feature extraction, more frames can result in stronger video features. Therefore, you can also sample 192*4=768 frames from the same video and get 768 features, then _resize_ to 192 features, leading to stronger performance. This 4 is the scale factor, meaning how many more frames you are sampling.

Based on the above explanation, you can find that the `scale_factor` has a similar effect of changing the input video fps. If the `scale_factor` is larger, the video fps will also be larger, resulting in more frames given the same duration.

On THUMOS, the window size is 768, so we will have 768 frames if the `scale_factor` is 1. If you want 1536 frames,  you can change the `scale_factor` to 2, leading to better performance. But of course, the memory will also be bigger.

**Comment by izikgo** [comment]
Thanks you for the explanation. When you say "resize  to 192 features", what exactly does that mean? The interpolation is done at the feature vector level?
Also, in the vision transformer `PatchEmbed` layer, the stride in the temporal is 2 (like the tubelet size). Isn't this effectively downsamping by a factor of 2 in the backbone?

**Comment by sming256** [comment]
Resize meaning we can use F.interpolate to resize the feature's T dimension from 768 to 192. Check [here](https://github.com/sming256/OpenTAD/blob/28286d786f0941c34bae690a90d140e0bb017ead/configs/adatad/anet/e2e_anet_videomae_s_192x4_160_adapter.py#L93).

The above explanation is an example assuming there is no temporal downsampling in the backbone. In VideoMAE, the temporal downsampling stride is 2. Therefore, given 768 frames, they will output a feature with the shape BxCx384, and we will resize the T dimension to 192.

**Comment by izikgo** [comment]
Understood. Thanks You!

**Comment by Free-Geter** [comment]
If there is downsampling in the backbone, for example, in the dataset setting used in `e2e_thoums_videomae_s_768x1_160_adapter.config`, will snippet_stride=4 be used to perform 4 times downsampling on the input video in the time dimension?

 If so, at this time, assuming the original video has N frames:
- If scale_factor=1 is set, only N/4*1 frames of the original video are input. 
- If scale_factor=2 is set, only N/4*2 frames of the original video are input, that is, half of the images. 
- If scale_factor=4 is set, only N/4*1 frames of the original video are input, that is, all the images. 

Next, VideoMAE (assuming kernel_size = (2,16,16), stride = (2,16,16)) will decompose all the input video into N/2 * W/16 * H/16 patches, then perform Embedding and encode, and finally the amount of output features is Batch_Size * N/2 * W/16 * H/16 = F . If F>windows_size, then F features will be compressed to windows_size features, otherwise, it will be upsampled to windows_size features. 

Is my understanding of the code above correct?

**Comment by sming256** [comment]
Your understanding is correct!
